<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <Description>Automation for voting levels in Zeepkist</Description>
        <Version>1.16.2</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <Authors>Hi Im Yolo</Authors>
        <PackageId>PlaylistVoting</PackageId>
    </PropertyGroup>


    <!-- NuGet-Paketabhängigkeiten -->
    <ItemGroup>
        <!-- BepInEx Abhängigkeiten -->
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.*"/>

        <!-- Weitere Plugins und Bibliotheken -->
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile"/>
        <PackageReference Include="Zeepkist.GameLibs" Version="16.67.1694"/>
        <PackageReference Include="ZeepSDK" Version="1.38.2"/>
    </ItemGroup>

    <!-- Bedingte Abhängigkeiten -->
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/>
    </ItemGroup><!-- Post-Build Scripts -->
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <!-- Delete the plugin directory if it exists -->
        <RemoveDir Directories="C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)"/>

        <!-- Create the plugin directory -->
        <MakeDir Directories="C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)"/>

        <!-- Copy DLL to the plugin directory -->
        <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)\$(ProjectName)-$(Version).dll&quot;"/>

        <!-- Create a zip file from the directory -->
        <Exec Command="powershell Compress-Archive -Path &quot;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)\*&quot; -DestinationPath &quot;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)-$(Version).zip&quot; -Force"/>
    </Target>

</Project>